
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul
    username: root
    password: 9156
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      # sql ??? ????? ?? ???? ????.
      # ?????? ?? ? ?? ????? ????.
      initialize-schema: embedded

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace